#!/usr/bin/env bash
# World wide web
info() {
	ld="$1"
	lsd="$2"

	ips=$(dig $lsd.$ld | grep -A1 ";; ANSWER SECTION:" | grep "$ld")
	_type=$(echo "$ips" | awk '{print $4}')
	_ip=$(echo "$ips" | awk '{print $5}')
	echo "The subdomain $lsd is a $_type record and points to $_ip"
}

d="$1"
sd="$2"

if [ -z "$sd" ]; then
	info "$d" "www"
	info "$d" "lb-01"
	info "$d" "web-01"
	info "$d" "web-02"
else
	info "$d" "$sd"
fi
