#!/usr/bin/env bash
# Bash script that transfers a file
# from our client to a server

no_args="$#"

if [ $no_args -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

file_path=$1
ip=$2
username=$3
ssh_key=$4

scp -o StrictHostKeyChecking=no "$file_path" -i "$ssh_key" "$username@$ip":~/
