#!/usr/bin/env bash
# Bash script that configures a new
# Ubuntu machine to respect above requirements
# this script will be run on the server itself)

apt-get update
apt-get install -y nginx
sudo mkdir -p /etc/nginx/sites-available
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
        echo "Hello World!";
    }
}
EOF

sudo service nginx restart
