#!/usr/bin/env bash
# Bash script that configures a new
# Ubuntu machine to respect above requirements
# this script will be run on the server itself)
sudo su
apt-get update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html;
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html index.html;
    server_name _;
    location / {
        try_files $uri $uri/ =404;
    }
}
EOF

service nginx restart
