#!/usr/bin/env bash
# Bash script that configures a new
# Ubuntu machine to respect above requirements
# this script will be run on the server itself)
sudo su
apt-get update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html;
echo "Ceci n'est pas une page" > /var/www/html/404.html;
printf %s "server {
listen 80;
listen [::]:80;

root /var/www/html;
index index.html index.htm index.nginx-debian.html;

server_name _;

location / {
try_files / =404;
}
location /redirect_me {
return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4i;
}
error_page 404 /404.html;
location = /404.html {
root /var/www/html/;
internal;
}

}" > /etc/nginx/sites-available/default
/etc/init.d/nginx start
