#!/usr/bin/env bash
# fix nginx on port :80
# Prepare your web servers

sudo apt remove nginx
sudo apt-get update
sudo apt-get -y install nginx
sudo rm /etc/nginx/sites-available/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
sleep 5
sudo service nginx restart
