#!/usr/bin/env bash
# a bash script that does a whole
# lot of junk
i=$$;
echo "$i" > /var/run/myscript.pid;
trap "echo 'I hate the kill command'; rm -f /var/run/myscript.pid; kill '$i'" SIGTERM;
trap "echo 'y u no love me?!'" si;
trap "rm -f '/var/run/myscript.pid'" sigquit;
trap "rm -f '/var/run/myscript.pid'" sigterm;
while ((1)); do
	echo "To infinity and beyond";
	sleep 2;
done;
