#!/usr/bin/env bash
# a bash script that does a whole
# lot of junk
i=$$;
echo "$i" > /var/run/myscript.pid;
trap "echo 'I hate the kill command'" SIGTERM;
trap "echo 'Y U no love me?!'" SIGINT;
trap "rm '/var/run/myscript.pid'" SIGQUIT;
trap "rm '/var/run/myscript.pid'" SIGTERM;
while ((1)); do
	echo "To infinity and beyond";
done;
