#!/usr/bin/env bash
# a script to automate setting up firewall
sudo apt update
sudo apt upgrade
sudo apt install ufw -y
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw allow 22/tcp
sudo ufw enable -y
sudo ufw status verbose
