#!/usr/bin/env bash
# reconfigure nginx
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i '/listen 80 default_server;/a listen 8080 default_server;' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
