#!/usr/bin/env bash
# reconfigure nginx
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo chmod 644 /etc/nginx/nginx.conf
sed -i '/listen 80;/a listen 8080;' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
sudo -u nginx service nginx restart
