#!/usr/bin/env bash
# reconfigure nginx
sudo apt-get update
sudo apt-get install nginx
sudo sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i '/listen 80;/a listen 8080;' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
sudo -u nginx service nginx restart
