#!/usr/bin/env bash
# reconfigure nginx
sudo apt-get install nginx
sudo sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
